name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup AWS SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_action.pem
          chmod 600 ~/.ssh/github_action.pem
          ssh-keyscan -H 54.234.102.65 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_action.pem ubuntu@ec2-13-250-32-243.ap-southeast-1.compute.amazonaws.com << 'EOF'
            cd /var/www/legalhub-go
            sudo git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
